apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi-node
spec:
  replicas: 3
  serviceName: energi-node
  selector:
    matchLabels:
      app: energi-node
  template:
    metadata:
      labels:
        app: energi-node
    spec:
      imagePullSecrets: 
      - name: dockersecret
      containers:
      - name: energi-node
        image: awskanojia/devops-challenge:latest
        ports:
        - containerPort: 39797
          name: rpc
        - containerPort: 39798
          name: p2p
        resources:
          requests:
            cpu: "0.5"  # Define minimum CPU required
            memory: "512Mi"  # Define minimum memory required
          limits:
            cpu: "1"  # Define maximum CPU limit
            memory: "1Gi"  # Define maximum memory limit
        volumeMounts:
        - name: data
          mountPath: /opt/  # Mount point for persistent volume
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: node-data-energi-node-0
  volumeClaimTemplates:
  - metadata:
      name: node-data-energi-node-0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi  # Request for 1GB storage
