name: Build and Scan Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t your-docker-username/your-docker-repo:latest \
            .

      - name: Scan Docker image with Trivy
        run: |
          docker run --rm -v $(pwd):/workdir aquasec/trivy your-docker-username/your-docker-repo:latest
