name: Build and Scan Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Specify your AWS region    

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t awskanojia/devops-challenge:latest \
            --push \
            .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.21.0/trivy_0.21.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.21.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker image with Trivy
        run: |
          docker pull awskanojia/devops-challenge:latest
          trivy image awskanojia/devops-challenge:latest  

      # - name: Deploy to EKS
      #   run: |
      #     aws eks update-kubeconfig --name devops-challenge --region ap-south-1
      #     kubectl get svc -A
      #     kubectl create secret docker-registry dockersecret \
      #        --docker-server=https://index.docker.io/v1/ \
      #        --docker-username=$DOCKERHUB_USERNAME \
      #        --docker-password=$DOCKERHUB_PASSWORD \
      #        --docker-email=aws.kanojia@gmail.com
      #     kubectl apply -f statefullset/app-statefullset.yaml
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Terraform Deploy
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform destroy -auto-approve

      